---
- hosts: all
  remote_user: root
  tasks:
    - name: Install libselinux as prerequisite for SELinux Ansible module
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - libselinux-python
        - libsemanage-python
    - name: Disable SELinux at next reboot
      selinux:
        state: disabled
    - name: Set SELinux in permissive mode until the machine is rebooted
      command: setenforce 0
      ignore_errors: true
      changed_when: false
      
    - name: Rebooting server
      reboot:
         msg: "Reboot initiated by Ansible"
    
